### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by jrisysback** [opensemanticsearch/open-semantic-search-server#11]
Hi,

I set up a Ubuntu 16.04 server and installed OSS (open-semantic-search_18.03.01.deb) via the complete .deb package.

When I try to create a crawler job via the website, I get an error message that the database cannot be opened.
![databse error](https://user-images.githubusercontent.com/37440036/37516932-208dc140-2910-11e8-81b8-da9046e8ff74.png)

I made some changes to the configurations.

![config_connector](https://user-images.githubusercontent.com/37440036/37517356-7293382a-2911-11e8-8ee6-1e1881a2da59.png)
![config_solr](https://user-images.githubusercontent.com/37440036/37517357-72b23c02-2911-11e8-821c-e773187e6de1.png)

Is there anything that I'm missing here?
Thanks
Jens

**Comment by jrisysback** [comment]
I found the solution. It was a permission problem. The owner of the dir "/var/lib/opensemanticsearch" was root but it need to be www-data.

**Comment by opensemanticsearch** [comment]
Added setting directory rights to postinst script of the package, so it should not happen again if building package from Git repository, which does'nt include user names of file rights.
