### ISSUE TITLE
xenial uses php7 and php7 has replaced split function with explode

### ISSUE THREAD

**Issue by clamor** [opensemanticsearch/open-semantic-search-server#2]
open-semantic-search-server-ubuntu_xenial_16.10.10.deb

it has to be replaced here:

/usr/share/solr-php-ui/templates/view.facets.php line 65

and here:

/usr/share/solr-php-ui/index.php lines 935 and 943

**Comment by opensemanticsearch** [comment]
Thank you very much!

Now [changed/upgraded](https://github.com/opensemanticsearch/solr-php-ui/commit/af9b5400e0c83c8a3677d5099a9e5794eca7074c)
