### ISSUE TITLE
xenial installs incompatible django 1.8.7 

### ISSUE THREAD

**Issue by clamor** [opensemanticsearch/open-semantic-search-server#3]
open-semantic-search-server-ubuntu_xenial_16.10.10.deb

There is a dependency in the .deb package which requires python-django to be installed. In Xenial the version to be installed is 1.8.7, which does not work with several django-views. However removing the dependency and installing django 1.7.7 via pip seems to resolve the problem.

**Comment by opensemanticsearch** [comment]
Since further Django development requires Python => 3, will test if planned search apps and ETL upgrade from Python 2.x to Python 3 (then moving to Github) will work on both.

If not maybe the DB format changed, so a python manage.py syncdb will be needed instead of prefilled DB file.

**Comment by opensemanticsearch** [comment]
Django apps [code](https://github.com/opensemanticsearch/open-semantic-search-apps/issues/1) is running on newest Ubuntu LTS.

Newest Ubuntu LTS standard Django has problems with the preshipped DB format/version.

Will be solved by more abstract [database initialization](https://github.com/opensemanticsearch/open-semantic-search-apps/issues/2)
